spring:
  application:
    name: springboot-01
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot01
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
